name: Bug Report
description: File a bug report to help us improve embedded-charts
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible.

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: What should have happened instead?
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: code-sample
    attributes:
      label: Minimal code sample
      description: If applicable, provide a minimal code sample that reproduces the issue
      render: rust
      placeholder: |
        use embedded_charts::prelude::*;
        
        // Your minimal reproduction code here

  - type: dropdown
    id: chart-type
    attributes:
      label: Chart type
      description: Which chart type is affected?
      options:
        - Line Chart
        - Bar Chart
        - Pie Chart
        - Scatter Chart
        - Gauge Chart
        - Stacked Charts
        - Custom Chart
        - Not chart-specific
        - Other
    validations:
      required: true

  - type: dropdown
    id: target-environment
    attributes:
      label: Target environment
      description: What environment are you targeting?
      options:
        - std (desktop/server)
        - no_std (embedded)
        - small-mcu (<64KB RAM)
        - medium-mcu (128-512KB RAM)
        - large-mcu (>512KB RAM)
        - Not sure
    validations:
      required: true

  - type: input
    id: rust-version
    attributes:
      label: Rust version
      description: What version of Rust are you using?
      placeholder: "1.70.0"
    validations:
      required: true

  - type: input
    id: crate-version
    attributes:
      label: embedded-charts version
      description: What version of embedded-charts are you using?
      placeholder: "0.1.0"
    validations:
      required: true

  - type: textarea
    id: features
    attributes:
      label: Feature flags
      description: Which feature flags are you using?
      placeholder: |
        default = ["std", "basic-charts", "integer-math"]
        # or
        features = ["small-mcu", "line", "bar"]

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the problem here, including screenshots if applicable.

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true